### ISSUE TITLE
Minor leftover: Please remove this comment

### ISSUE THREAD

**Issue by mikekgr** [khoih-prog/BlynkGSM_Manager#2]
In both examples you have left one of my comment that is not valid in your examples ( both for ESP32 &ESP8266 ) :

/// Change this from 1 to 0 to test the functionality between Blynk only and BLynk with HTTPClientHandle that does not work ... ///

Thanks and Best Regards,
Mike Kranidis

**Comment by khoih-prog** [comment]
Done. Did you have a chance to test? 
It has some mods to eliminate board immediately resetting if GSM modem is not present or not working. 
This must have been taken care in TinyGSM library.

Thanks and Regards,
KH

**Comment by mikekgr** [comment]
> Done. Did you have a chance to test?
> 

No, very sorry... I will test it out in my first opportunity and I will let you know. I have lot of things to take care of these days...

Thanks and Best Regards,
Mike Kranidis
