### ISSUE TITLE
Change Auth Token

### ISSUE THREAD

**Issue by trieu94** [khoih-prog/BlynkGSM_Manager#3]
How can i reset eeprom after i refresh auth token, because board still connected to network, but can not connect to blynk because token changed already.
I mean how can i reset WM to input new key, and how can i put wifi name and pass when board in AP mode? thanks

**Comment by khoih-prog** [comment]
Pls read 

**So, how it works?**
If it detects no valid stored Credentials or it cannot connect to the Blynk server in 30 seconds, it will switch to Configuration Mode. You will see your built-in LED turned ON. In Configuration Mode, it starts a WiFi access point called ESP_xxxxxx. Connect to it using password MyESP_xxxxxx .
